on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 安装依赖并构建
        run: |
          npm install
          npm run build
      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4.1.5
        with:
          branch: gh-pages
          folder: build